releases:
    version:   "5.1.1"
    directory: "https://www.apache.org/dist/cordova/"
    note:      "Apache Cordova 5.1.1"

sitemap: {
    "about": {
        "title": "About Cordova",
        "url": "/index.html#about"
    },
    "artwork": {
        "title": "Artwork",
        "url": "/artwork.html"
    },
    "download": {
        "title": "Download",
        "url": "/index.html#download"
    },
    "mailing-list": {
        "title": "Mailing List",
        "url": "/index.html#mailing-list"
    },
    "docs": {
        "title": "Documentation",
        "url": "http://cordova.apache.org/docs/en/5.0.0/"
    },
    "general": [
    {
        "title": "Apache Project Page",
        "url": "http://projects.apache.org/projects/cordova.html"
    },
    {
        "title": "License",
        "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
    ],
    "dev": [
    {
        "title": "Source Code",
        "url": "https://git-wip-us.apache.org/repos/asf"
    },
    {
        "title": "Issue Tracker",
        "url": "https://issues.apache.org/jira/browse/CB"
    },
    {
        "title": "Wiki",
        "url": "http://wiki.apache.org/cordova/"
    }
    ],
    "asf": [
    {
        "title": "About ASF",
        "url": "http://www.apache.org/"
    },
    {
        "title": "Thanks",
        "url": "http://www.apache.org/foundation/thanks.html"
    },
    {
        "title": "Become a Sponsor",
        "url": "http://www.apache.org/foundation/sponsorship.html"
    },
    {
        "title": "Security",
        "url": "http://www.apache.org/security/"
    }
    ]
}

repos: {
    platforms: [
        {
            "name": "Amazon Fire OS",
            "github": "https://github.com/apache/cordova-amazon-fireos",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-amazon-fireos.git;a=summary",
            "css": "first"
        },
        {
            "name": "Android",
            "github": "https://github.com/apache/cordova-android",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-android.git;a=summary"
        },
        {
            "name": "Bada",
            "github": "https://github.com/apache/cordova-bada",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-bada.git;a=summary"
        },
        {
            "name": "Blackberry",
            "github": "https://github.com/apache/cordova-blackberry",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-blackberry.git;a=summary"
        },
        {
            "name": "FirefoxOS",
            "github": "https://github.com/apache/cordova-firefoxos",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-firefoxos.git;a=summary"
        },
        {
            "name": "iOS",
            "github": "https://github.com/apache/cordova-ios",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-ios.git;a=summary"
        },
        {
            "name": "Mac OS X",
            "github": "https://github.com/apache/cordova-osx",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-osx.git;a=summary"
        },
        {
            "name": "Qt",
            "github": "https://github.com/apache/cordova-qt",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-qt.git;a=summary"
        },
        {
            "name": "Tizen",
            "github": "https://github.com/apache/cordova-tizen",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-tizen.git;a=summary"
        },
        {
            "name": "Ubuntu",
            "github": "https://github.com/apache/cordova-ubuntu",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-ubuntu.git;a=summary"
        },
        {
            "name": "WebOS",
            "github": "https://github.com/apache/cordova-webos",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-webos.git;a=summary"
        },
        {
            "name": "Windows (desktop)",
            "github": "https://github.com/apache/cordova-windows",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-windows.git;a=summary"
        },
        {
            "name": "Windows Phone 7",
            "github": "https://github.com/apache/cordova-wp7",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-wp7.git;a=summary"
        },
        {
            "name": "Windows Phone 8",
            "github": "https://github.com/apache/cordova-wp8",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-wp8.git;a=summary"
        },
        {
            "name": "Browser",
            "github": "https://github.com/apache/cordova-browser",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-browser.git;a=summary"
        }
    ],
    plugins: [
        {
            "name": "Battery Status",
            "github": "https://github.com/apache/cordova-plugin-battery-status",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-battery-status.git;a=summary"
        },
        {
            "name": "Camera",
            "github": "https://github.com/apache/cordova-plugin-camera",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-camera.git;a=summary"
        },
        {
            "name": "Console",
            "github": "https://github.com/apache/cordova-plugin-console",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-console.git;a=summary"
        },
        {
            "name": "Contacts",
            "github": "https://github.com/apache/cordova-plugin-contacts",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-contacts.git;a=summary"
        },
        {
            "name": "Device",
            "github": "https://github.com/apache/cordova-plugin-device",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-device.git;a=summary"
        },
        {
            "name": "Device Motion",
            "github": "https://github.com/apache/cordova-plugin-device-motion",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-device-motion.git;a=summary"
        },
        {
            "name": "Device Orientation",
            "github": "https://github.com/apache/cordova-plugin-device-orientation",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-device-orientation.git;a=summary"
        },
        {
            "name": "Dialogs",
            "github": "https://github.com/apache/cordova-plugin-dialogs",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-dialogs.git;a=summary"
        },
        {
            "name": "File",
            "github": "https://github.com/apache/cordova-plugin-file",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-file.git;a=summary"
        },
        {
            "name": "File Transfer",
            "github": "https://github.com/apache/cordova-plugin-file-transfer",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-file-transfer.git;a=summary"
        },
        {
            "name": "Geolocation",
            "github": "https://github.com/apache/cordova-plugin-geolocation",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-geolocation.git;a=summary"
        },
        {
            "name": "Globalization",
            "github": "https://github.com/apache/cordova-plugin-globalization",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-globalization.git;a=summary"
        },
        {
            "name": "In-App Browser",
            "github": "https://github.com/apache/cordova-plugin-inappbrowser",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-inappbrowser.git;a=summary"
        },
        {
            "name": "Media",
            "github": "https://github.com/apache/cordova-plugin-media",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-media.git;a=summary"
        },
        {
            "name": "Media Capture",
            "github": "https://github.com/apache/cordova-plugin-media-capture",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-media-capture.git;a=summary"
        },
        {
            "name": "Network Information",
            "github": "https://github.com/apache/cordova-plugin-network-information",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-network-information.git;a=summary"
        },
        {
            "name": "Splashscreen",
            "github": "https://github.com/apache/cordova-plugin-splashscreen",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-splashscreen.git;a=summary"
        },
        {
            "name": "Statusbar",
            "github": "https://github.com/apache/cordova-plugin-statusbar",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-statusbar.git;a=summary"
        },
        {
            "name": "Vibration",
            "github": "https://github.com/apache/cordova-plugin-vibration",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-vibration.git;a=summary"
        }
    ],
    other: [
        {
            "name": "Cordova Docs",
            "github": "https://github.com/apache/cordova-docs",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-docs.git;a=summary"
        },
        {
            "name": "Cordova JS (JavaScript API)",
            "github": "https://github.com/apache/cordova-js",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-js.git;a=summary"
        },
        {
            "name": "Cordova CLI",
            "github": "https://github.com/apache/cordova-cli",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-cli.git;a=summary"
        },
        {
            "name": "Cordova Plugman (Plugin Manager)",
            "github": "https://github.com/apache/cordova-plugman",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-plugman.git;a=summary"
        },
        {
            "name": "Cordova Lib (Common Code)",
            "github": "https://github.com/apache/cordova-lib",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-lib.git;a=summary"
        },
        {
            "name": "Cordova Mobile Spec (Test Suite)",
            "github": "https://github.com/apache/cordova-mobile-spec",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-mobile-spec.git;a=summary"
        },
        {
            "name": "Cordova Medic (Test Automation)",
            "github": "https://github.com/apache/cordova-medic",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-medic.git;a=summary"
        },
        {
            "name": "Weinre (Web Inspector Remote)",
            "github": "https://github.com/apache/cordova-weinre",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-weinre.git;a=summary"
        },
        {
            "name": "Cordova App Harness",
            "github": "https://github.com/apache/cordova-app-harness",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-app-harness.git;a=summary"
        },
        {
            "name": "Cordova Hello World (Sample App)",
            "github": "https://github.com/apache/cordova-app-hello-world",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-app-hello-world.git;a=summary"
        },
        {
            "name": "Cordova Coho (Release Tool)",
            "github": "https://github.com/apache/cordova-coho",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-coho.git;a=summary"
        },
        {
            "name": "Cordova Registry Web (Plugin Registry UI)",
            "github": "https://github.com/apache/cordova-registry-web",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-registry-web.git;a=summary"
        },
        {
            "name": "Cordova Registry (Plugin Registry App)",
            "github": "https://github.com/apache/cordova-registry",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-registry.git;a=summary"
        },
        {
            "name": "Cordova Labs (Experimental Content)",
            "github": "https://github.com/apache/cordova-labs",
            "apache": "https://git-wip-us.apache.org/repos/asf?p=cordova-labs.git;a=summary"
        }
    ]
}
