name: build test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Environment Configure
        run: |
          npm install

      - name: Test
        run: npm test

      - name: Dev Build
        run: npm run build
